apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mfe-release
  namespace: argo
spec:
  serviceAccountName: argo-workflow
  entrypoint: pipeline
  arguments:
    parameters:
      - name: repo
      - name: tag
      - name: service
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: pipeline
      dag:
        tasks:
          - name: clone
            template: git-clone
          - name: build-push
            template: kaniko-build
            dependencies: [clone]

    - name: git-clone
      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - |
            git clone --depth 1 --branch {{workflow.parameters.tag}} \
              https://github.com/{{workflow.parameters.repo}}.git /work/src
            echo "Cloned {{workflow.parameters.repo}} at {{workflow.parameters.tag}}"
            ls /work/src/
        volumeMounts:
          - name: work
            mountPath: /work

    - name: kaniko-build
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --dockerfile=/work/src/Dockerfile
          - --context=/work/src
          - --destination=registry.registry.svc.cluster.local:5000/{{workflow.parameters.service}}:{{workflow.parameters.tag}}
          - --insecure
        volumeMounts:
          - name: work
            mountPath: /work
