name: "Record Deploy Event"
description: "Writes a deploy event into mf-infra/events and pushes it to the mf-infra repo"

inputs:
  token:
    required: true
  app_name:
    required: true
  environment:
    required: true
  deploy_url:
    required: true
  status:
    required: false
    default: "success"
  infra_ref:
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Validate token
      shell: bash
      run: |
        if [ -z "${{ inputs.token }}" ]; then
          echo "Missing required input: token" >&2
          exit 1
        fi

        CODE="$(curl -sS -o /dev/null -w "%{http_code}" \
          -H "Authorization: token ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/kristjanjansen/mf-infra || echo "000")"

        if [ "${CODE}" != "200" ]; then
          echo "Token validation failed: GitHub API responded with HTTP ${CODE} for repo kristjanjansen/mf-infra" >&2
          echo "Ensure the token has repository access to kristjanjansen/mf-infra and Contents: read/write." >&2
          exit 1
        fi

    - name: Checkout mf-infra
      uses: actions/checkout@v4
      with:
        repository: kristjanjansen/mf-infra
        path: mf-infra
        ref: main
        token: ${{ inputs.token }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Record event
      shell: bash
      run: bash "${GITHUB_ACTION_PATH}/record.sh"
      env:
        INPUT_APP_NAME: ${{ inputs.app_name }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_DEPLOY_URL: ${{ inputs.deploy_url }}
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_INFRA_REF: ${{ inputs.infra_ref }}
