name: "Deploy Preview Environment"
description: "Deploys a PR preview to Kubernetes"

inputs:
  service_name:
    required: true
  port:
    required: true
  namespace:
    required: true
  image:
    required: true
  host:
    required: true

runs:
  using: "composite"
  steps:
    - run: bash "${GITHUB_ACTION_PATH}/deploy.sh"
      shell: bash
      env:
        INPUT_SERVICE_NAME: ${{ inputs.service_name }}
        INPUT_PORT: ${{ inputs.port }}
        INPUT_NAMESPACE: ${{ inputs.namespace }}
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_HOST: ${{ inputs.host }}
